services:
  example-app:
    image: openjdk:11-jre-slim
    container_name: example-app
    volumes:
      - ./target/example-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "5000:5000"
    command: ["java", "-jar", "/app/app.jar"]
    depends_on:
      - example-db

  example-db:
    image: mysql:latest
    container_name: example-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: euge
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
